import {
  readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync,
} from 'node:fs';
import { join, resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';
import {
  splitFrontmatter, readingMinutes, stripLeadingH1, sitemapXml, extractFaq,
  validateDates, validateSeoTitle, llmsTxt, llmsFullTxt, parseChangelog, xmlEscape,
} from './content.util.mjs';
import { externalLinkExtension } from './build-content.util.mjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const frontendRoot = resolve(scriptDir, '..');
const repoRoot = resolve(frontendRoot, '..');
const contentDir = resolve(repoRoot, 'content');
const SITE = JSON.parse(readFileSync(resolve(frontendRoot, 'src/app/core/site-identity.json'), 'utf8'));
const outFile = resolve(
  frontendRoot,
  'src/app/features/marketing/content.generated.ts',
);

marked.setOptions({ gfm: true, breaks: false });
marked.use(externalLinkExtension());

function loadDir(kind) {
  const dir = join(contentDir, kind);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .map((f) => {
      const raw = readFileSync(join(dir, f), 'utf8');
      const { data, body } = splitFrontmatter(raw);
      const slug = data.slug || basename(f, '.md');
      const { date, updated } = validateDates(data, f);
      const seoTitle = validateSeoTitle(data.seoTitle, f);
      const markdown = stripLeadingH1(body);
      const doc = {
        slug,
        title: data.title || slug,
        description: data.description || '',
        date,
        category: data.category || '',
        order: Number.parseInt(data.order ?? '0', 10) || 0,
        readingMinutes: readingMinutes(body),
        faq: extractFaq(body),
        html: marked.parse(markdown),
        markdown, // build-only: llms-full.txt; stripped by serialize()
      };
      if (updated) doc.updated = updated;
      if (seoTitle) doc.seoTitle = seoTitle;
      if (kind === 'blog') doc.ogImage = `https://tuliplot.com/banners/${slug}-og.png`;
      return doc;
    });
}

function sortDocs(kind, docs) {
  if (kind === 'guides') {
    return docs.sort(
      (a, b) => a.order - b.order || a.title.localeCompare(b.title),
    );
  }
  return docs.sort((a, b) => b.date.localeCompare(a.date));
}

function serialize(list) {
  // strip build-only fields; ContentDoc does not carry them
  return JSON.stringify(
    list.map(({ order, markdown, ...rest }) => rest),
    null,
    2,
  );
}

const guides = sortDocs('guides', loadDir('guides'));
const posts = sortDocs('blog', loadDir('blog'));

function loadChangelog() {
  const raw = readFileSync(resolve(contentDir, 'changelog.md'), 'utf8');
  const { data, body } = splitFrontmatter(raw);
  const { entries, newest } = parseChangelog(body);
  const html = entries
    .map((e) =>
      `<h2><time datetime="${e.date}">${e.date}</time> — ${xmlEscape(e.title)}</h2>\n` +
      marked.parse(e.markdown),
    )
    .join('\n');
  return { title: data.title || 'Changelog', description: data.description || '', html, updated: newest };
}
const changelog = loadChangelog();

const banner =
  '// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.\n';
const out =
  banner +
  `import { ContentDoc, ChangelogDoc } from './content.model';\n\n` +
  `export const GUIDES: ContentDoc[] = ${serialize(guides)};\n\n` +
  `export const POSTS: ContentDoc[] = ${serialize(posts)};\n\n` +
  `export const CHANGELOG: ChangelogDoc = ${JSON.stringify(changelog, null, 2)};\n`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, out, 'utf8');
console.log(
  `content: ${guides.length} guides, ${posts.length} posts -> ${outFile}`,
);

// Static pages: sitemap lastmod + the llms.txt "Pages" section.
// RULE: when the copy of a static page changes, bump its lastmod here in the same PR.
const STATIC_PAGES = [
  { path: '/', title: 'Home', description: SITE.sentence, lastmod: '2026-08-02' },
  { path: '/try', title: 'Try TulipLot without an account', description: 'Two live cells with no signup; they move into a free account when you create one.', lastmod: '2026-08-15' },
  { path: '/about', title: 'About TulipLot', description: 'Why TulipLot exists, how it works, and what Try, Free, and Premium include.', lastmod: '2026-08-02' },
  { path: '/changelog', title: 'Changelog', description: changelog.description, lastmod: changelog.updated },
  { path: '/guides', title: 'Guides', description: 'Step-by-step help: your first grid, sites that refuse to embed, and Premium vs Free.', lastmod: '2026-08-01' },
  { path: '/blog', title: 'Blog', description: 'Tab overload, browser dashboards, comparisons, and product news.', lastmod: '2026-08-01' },
  { path: '/contact', title: 'Contact', description: 'How to reach the team for support, billing, feedback, and privacy requests.', lastmod: '2026-08-01' },
  { path: '/privacy', title: 'Privacy Policy', description: 'What TulipLot collects, how ads and cookies work, and your choices.', lastmod: '2026-08-01' },
  { path: '/terms', title: 'Terms of Service', description: 'The terms that govern your use of TulipLot.', lastmod: '2026-08-01' },
];
const withSlash = (r) => `https://tuliplot.com${r === '/' ? '/' : r + '/'}`;
const entries = [
  ...STATIC_PAGES.map((p) => ({ loc: withSlash(p.path), lastmod: p.lastmod })),
  ...guides.map((g) => ({ loc: withSlash(`/guides/${g.slug}`), lastmod: g.updated ?? g.date })),
  ...posts.map((p) => ({ loc: withSlash(`/blog/${p.slug}`), lastmod: p.updated ?? p.date })),
];
writeFileSync(resolve(frontendRoot, 'public/sitemap.xml'), sitemapXml(entries), 'utf8');
console.log(`sitemap: ${entries.length} urls -> public/sitemap.xml`);

const llmsDoc = (basePath) => (d) => ({
  title: d.title, url: withSlash(`${basePath}/${d.slug}`), description: d.description,
  date: d.date, updated: d.updated, markdown: d.markdown,
});
const llmsGuides = guides.map(llmsDoc('/guides'));
const llmsPosts = posts.map(llmsDoc('/blog'));
const llmsPages = STATIC_PAGES.map((p) => ({ title: p.title, url: withSlash(p.path), description: p.description }));
writeFileSync(resolve(frontendRoot, 'public/llms.txt'), llmsTxt({ site: SITE, guides: llmsGuides, posts: llmsPosts, pages: llmsPages }), 'utf8');
writeFileSync(resolve(frontendRoot, 'public/llms-full.txt'), llmsFullTxt({ site: SITE, guides: llmsGuides, posts: llmsPosts }), 'utf8');
console.log('llms: public/llms.txt, public/llms-full.txt');
