import {
  readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync,
} from 'node:fs';
import { join, resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';
import { splitFrontmatter, readingMinutes, stripLeadingH1, sitemapXml, extractFaq } from './content.util.mjs';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const frontendRoot = resolve(scriptDir, '..');
const repoRoot = resolve(frontendRoot, '..');
const contentDir = resolve(repoRoot, 'content');
const outFile = resolve(
  frontendRoot,
  'src/app/features/marketing/content.generated.ts',
);

marked.setOptions({ gfm: true, breaks: false });

function requireDate(date, file) {
  if (!date || !/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    throw new Error(`content: ${file} is missing a valid frontmatter date (YYYY-MM-DD)`);
  }
  return date;
}

function loadDir(kind) {
  const dir = join(contentDir, kind);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .map((f) => {
      const raw = readFileSync(join(dir, f), 'utf8');
      const { data, body } = splitFrontmatter(raw);
      const slug = data.slug || basename(f, '.md');
      return {
        slug,
        title: data.title || slug,
        description: data.description || '',
        date: requireDate(data.date, f),
        category: data.category || '',
        order: Number.parseInt(data.order ?? '0', 10) || 0,
        readingMinutes: readingMinutes(body),
        faq: extractFaq(body),
        html: marked.parse(stripLeadingH1(body)),
      };
    });
}

function sortDocs(kind, docs) {
  if (kind === 'guides') {
    return docs.sort(
      (a, b) => a.order - b.order || a.title.localeCompare(b.title),
    );
  }
  return docs.sort((a, b) => b.date.localeCompare(a.date));
}

function serialize(list) {
  // strip the build-only `order` field; ContentDoc does not carry it
  return JSON.stringify(
    list.map(({ order, ...rest }) => rest),
    null,
    2,
  );
}

const guides = sortDocs('guides', loadDir('guides'));
const posts = sortDocs('blog', loadDir('blog'));

const banner =
  '// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.\n';
const out =
  banner +
  `import { ContentDoc } from './content.model';\n\n` +
  `export const GUIDES: ContentDoc[] = ${serialize(guides)};\n\n` +
  `export const POSTS: ContentDoc[] = ${serialize(posts)};\n`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, out, 'utf8');
console.log(
  `content: ${guides.length} guides, ${posts.length} posts -> ${outFile}`,
);

const staticRoutes = ['/', '/about', '/privacy', '/terms', '/contact', '/guides', '/blog', '/try'];
const STATIC_LASTMOD = '2026-08-01'; // bump when static-page copy changes
const withSlash = (r) => `https://tuliplot.com${r === '/' ? '/' : r + '/'}`;
const entries = [
  ...staticRoutes.map((r) => ({ loc: withSlash(r), lastmod: STATIC_LASTMOD })),
  ...guides.map((g) => ({ loc: withSlash(`/guides/${g.slug}`), lastmod: g.date })),
  ...posts.map((p) => ({ loc: withSlash(`/blog/${p.slug}`), lastmod: p.date })),
];
writeFileSync(resolve(frontendRoot, 'public/sitemap.xml'), sitemapXml(entries), 'utf8');
console.log(`sitemap: ${entries.length} urls -> public/sitemap.xml`);
