// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
import { ContentDoc } from './content.model';

export const GUIDES: ContentDoc[] = [
  {
    "slug": "getting-started",
    "title": "Getting started with TulipLot",
    "description": "Create your account, arrange your first grid, and add your most-used apps in five minutes.",
    "date": "2026-06-01",
    "category": "Basics",
    "readingMinutes": 1,
    "html": "<p>TulipLot gives you a fixed <strong>3×2 grid</strong> — six cells, each hosting a live web\napp. This guide walks you from sign-up to a working dashboard.</p>\n<h2>1. Create your account</h2>\n<p>Sign up with email and a password, or use <strong>Sign in with Google</strong>. Your\ndashboard is tied to your account and syncs wherever you log in.</p>\n<h2>2. Add your first app</h2>\n<p>Click any empty cell and choose <strong>Add a site</strong>. Pick from the curated catalog\n(Gmail, Google Calendar, Trello, and more) or paste any HTTPS URL. TulipLot\nvalidates the URL and loads it inside a sandboxed frame.</p>\n<h2>3. Arrange the grid</h2>\n<p>Drag any cell onto another to <strong>swap</strong> their positions. The layout is fixed at\nsix cells, so you always know where each app lives.</p>\n<h2>4. Free vs Premium</h2>\n<p>On the free plan, the bottom-right cell shows a single ad and you get five\nusable cells. Upgrading to Premium removes the ad and unlocks all six.</p>\n<p>You are ready to go. The next guide covers adding sites that normally refuse to\nbe embedded.</p>\n"
  },
  {
    "slug": "add-any-site",
    "title": "Adding sites that refuse to be framed",
    "description": "Some sites block embedding. Here is how the TulipLot Chrome companion unlocks them safely.",
    "date": "2026-06-08",
    "category": "Advanced",
    "readingMinutes": 1,
    "html": "<p>Many popular sites send headers (<code>X-Frame-Options</code>, <code>Content-Security-Policy: frame-ancestors</code>) that stop them from loading inside another page. TulipLot\nhandles this gracefully.</p>\n<h2>Detecting a blocked site</h2>\n<p>When a cell fails to load, TulipLot shows a <strong>needs extension</strong> or <strong>open in a\ntab</strong> state instead of a broken frame.</p>\n<h2>Installing the Chrome companion</h2>\n<p>The optional TulipLot companion is a Chrome MV3 extension. It strips\nframe-blocking headers <strong>only for frames inside your dashboard</strong>, scoped to the\n<code>tuliplot.com</code> origin, and only for sites you explicitly allow.</p>\n<ol>\n<li>Install the companion from the Chrome Web Store.</li>\n<li>When a cell needs it, click <strong>Allow this site</strong> — Chrome asks for permission\nfor that specific site.</li>\n<li>The cell reloads and composites into your grid.</li>\n</ol>\n<h2>What still cannot be embedded</h2>\n<p>Major provider logins (Google, Microsoft, Meta) refuse to be framed even with\nheaders stripped, and some cookies only work in a top-level window. For those,\nTulipLot offers <strong>open in a real window</strong>. This is expected — the companion is\nan unlock, not a guarantee.</p>\n"
  },
  {
    "slug": "premium-vs-free",
    "title": "Premium vs Free — what you get",
    "description": "A side-by-side of the free plan and Premium, and how upgrading and downgrading work.",
    "date": "2026-06-15",
    "category": "Billing",
    "readingMinutes": 1,
    "html": "<p>TulipLot is free to use. Premium is an optional subscription that removes ads\nand unlocks the sixth cell.</p>\n<h2>Free plan</h2>\n<ul>\n<li>Five usable cells.</li>\n<li>One advertising cell (fixed bottom-right).</li>\n<li>Full drag-to-swap, catalog, and companion-extension support.</li>\n</ul>\n<h2>Premium plan</h2>\n<ul>\n<li>All six cells usable — no ad slot.</li>\n<li>No advertising cookies.</li>\n<li>Everything in the free plan.</li>\n</ul>\n<h2>Upgrading</h2>\n<p>Click <strong>Remove ad — go Premium</strong>. You are taken to Stripe Checkout. When\npayment succeeds, your account flips to Premium and the ad disappears.</p>\n<h2>Downgrading</h2>\n<p>Cancel anytime through the Stripe billing portal. When Premium ends, the\nbottom-right cell becomes the ad slot again; any app you had there moves to the\nfirst empty slot.</p>\n"
  }
];

export const POSTS: ContentDoc[] = [
  {
    "slug": "dashboard-productivity-tips",
    "title": "Five ways to lay out a productive dashboard",
    "description": "Practical patterns for arranging your six cells so the important stuff is always in view.",
    "date": "2026-07-10",
    "category": "Tips",
    "readingMinutes": 1,
    "html": "<p>Six cells is enough for a focused command center — if you arrange them with\nintent. Here are patterns that work.</p>\n<h2>1. Put your inbox top-left</h2>\n<p>We read screens top-left first. Give that spot to whatever you check most —\nusually email or chat.</p>\n<h2>2. Group by rhythm, not by app type</h2>\n<p>Cluster the things you glance at constantly (calendar, tasks) apart from the\nthings you dip into occasionally (docs, analytics).</p>\n<h2>3. Keep one “focus” cell</h2>\n<p>Reserve a cell for whatever you are actively working in today, and swap it as\nyour focus changes.</p>\n<h2>4. Use the companion sparingly</h2>\n<p>Only unlock the sites you truly need composited. Fewer heavy frames means a\nsnappier grid.</p>\n<h2>5. Let quiet cells sleep</h2>\n<p>TulipLot unmounts cells you are not looking at to save memory. Put rarely-used\napps where they can rest.</p>\n<p>Small layout choices compound. Spend five minutes arranging, save an hour of\nfriction.</p>\n"
  },
  {
    "slug": "why-we-built-tuliplot",
    "title": "Why we built TulipLot",
    "description": "The tab-overload problem, and why a fixed grid beats a wall of browser tabs.",
    "date": "2026-07-01",
    "category": "Product",
    "readingMinutes": 1,
    "html": "<p>Most of us spend the workday inside a handful of web apps — email, a calendar,\na project board, chat, a dashboard or two. Yet we access them through a\nsprawling, ever-shifting wall of browser tabs.</p>\n<h2>The cost of tab-hunting</h2>\n<p>Every context switch has a price: the second spent finding the right tab, the\nfocus lost re-orienting, the tab that quietly reloaded and logged you out.\nMultiply that across a day and the drag is real.</p>\n<h2>A fixed place for everything</h2>\n<p>TulipLot replaces the tab wall with a stable 3×2 grid. Each app has a home. You\narrange it once and your eyes learn where things are. Nothing moves unless you\nmove it.</p>\n<h2>Built for the real web</h2>\n<p>The hard part is that the web actively resists this — most sites refuse to be\nembedded. We solve it with a hybrid model: composite what we can directly, and\nuse an optional Chrome companion to unlock the rest, always scoped narrowly and\nalways under your control.</p>\n<p>That is TulipLot: one window, your whole workday.</p>\n"
  }
];
